import { Chat, ServiceItem, Patient, ExamItem } from './types'

export const mockPatients: Patient[] = [
  {
    id: 'p1',
    name: 'Ana Souza',
    contact: '(11) 98765-4321',
    email: 'ana.souza@email.com',
    cpf: '111.222.333-44',
    lastExam: 'Hemograma Completo',
    date: '12/10/2023',
    status: 'Concluído',
    exams: [
      {
        id: 'e1',
        name: 'Hemograma Completo',
        date: '12/10/2023',
        result: 'Normal',
        status: 'Concluído',
      },
      {
        id: 'e2',
        name: 'Glicemia em Jejum',
        date: '12/10/2023',
        result: '95 mg/dL',
        status: 'Concluído',
      },
    ],
    chats: [
      {
        id: 'ch1',
        date: '10/10/2023',
        summary: 'Dúvidas sobre o preparo para hemograma',
        status: 'Resolvido',
      },
    ],
  },
  {
    id: 'p2',
    name: 'Carlos Mendes',
    contact: '(11) 91234-5678',
    email: 'carlos.mendes@email.com',
    cpf: '222.333.444-55',
    lastExam: 'Espermograma',
    date: '15/01/2024',
    status: 'Ativo',
    exams: [
      {
        id: 'e3',
        name: 'Espermograma',
        date: '15/01/2024',
        result: 'Aguardando Análise',
        status: 'Pendente',
      },
    ],
    chats: [
      {
        id: 'ch2',
        date: '12/01/2024',
        summary: 'Agendamento e orientações do exame',
        status: 'Resolvido',
      },
    ],
  },
  {
    id: 'p3',
    name: 'Mariana Silva',
    contact: '(11) 99988-7766',
    email: 'mariana.s@email.com',
    cpf: '333.444.555-66',
    lastExam: 'Preventivo',
    date: '20/02/2024',
    status: 'Pendente',
    exams: [{ id: 'e4', name: 'Preventivo', date: '20/02/2024', result: '-', status: 'Agendado' }],
    chats: [
      {
        id: 'ch3',
        date: '15/02/2024',
        summary: 'Confirmação de agendamento online',
        status: 'Resolvido',
      },
    ],
  },
  {
    id: 'p4',
    name: 'João Pedro',
    contact: '(11) 97777-6666',
    lastExam: 'Exame Toxicológico',
    date: '15/02/2024',
    status: 'Concluído',
  },
  {
    id: 'p5',
    name: 'Lucia Fernandes',
    contact: '(11) 94444-3333',
    lastExam: 'Citologia',
    date: '10/03/2024',
    status: 'Pendente',
  },
  {
    id: 'p6',
    name: 'Roberto Alves',
    contact: '(11) 95555-2222',
    lastExam: 'Eletrocardiograma',
    date: '05/01/2024',
    status: 'Ativo',
  },
]

export const mockChats: Chat[] = [
  {
    id: 'c1',
    contactName: 'Maria Silva',
    platform: 'whatsapp',
    lineName: 'Clínica Principal (55 11 9999-0001)',
    unreadCount: 2,
    status: 'pending_human',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=1',
    notes: 'Paciente diabética, requer horários matutinos.',
    history: ['Hemograma Completo (12/10/2023)', 'Consulta Cardiologia (05/01/2024)'],
    followUpStep: 0,
    lastActivity: '10:35',
    messages: [
      {
        id: 'm1',
        text: 'Olá, gostaria de saber o valor do ecocardiograma.',
        sender: 'user',
        timestamp: '10:30',
        type: 'text',
      },
      {
        id: 'm2',
        text: 'Olá! O valor do Ecocardiograma é R$ 250,00. Gostaria de agendar? Lembrando que nossa clínica possui excelência em atendimento.',
        sender: 'ai',
        timestamp: '10:30',
        type: 'text',
      },
      {
        id: 'm3',
        text: 'Sim, mas preciso saber se o Dr. Roberto atende amanhã.',
        sender: 'user',
        timestamp: '10:32',
        type: 'text',
      },
      {
        id: 'm4',
        text: 'Não tenho acesso à agenda específica do Dr. Roberto no momento. Vou transferir você para um de nossos atendentes.',
        sender: 'ai',
        timestamp: '10:32',
        type: 'text',
      },
      { id: 'm5', text: 'Por favor, aguarde.', sender: 'user', timestamp: '10:35', type: 'text' },
    ],
  },
  {
    id: 'c2',
    contactName: 'João Pedro',
    platform: 'instagram',
    lineName: '@clinicamulticanal',
    unreadCount: 0,
    status: 'active',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
    history: ['Exame Toxicológico (15/02/2024)'],
    followUpStep: 3,
    lastActivity: 'Ontem',
    surveyResult: 5,
    patientData: {
      name: 'João Pedro de Souza',
      dob: '22/08/1992',
      cpf: '111.222.333-44',
      address: 'Rua Augusta, 500, São Paulo',
      coverageType: 'Particular',
    },
    messages: [
      {
        id: 'm1',
        text: 'Qual o preparo para exame de sangue comum?',
        sender: 'user',
        timestamp: 'Ontem 09:15',
        type: 'text',
      },
      {
        id: 'm2',
        text: 'Para o hemograma completo, a instrução de preparo pré-analítico é jejum de 8 a 12 horas. Você pode beber água moderadamente.\n\nLembro que nosso laboratório possui a classificação "Padrão Ouro" pelo PNCQ, o que garante rigorosos padrões internacionais de qualidade e máxima confiabilidade nos resultados.\n\nGostaria de agendar na clínica ou prefere a nossa opção de Coleta Domiciliar, para realizar seu exame com todo o conforto e conveniência em casa?',
        sender: 'ai',
        timestamp: 'Ontem 09:15',
        type: 'text',
      },
      {
        id: 'm3',
        text: 'Olá João, ainda tem dúvidas sobre o preparo do seu exame? Posso ajudar a agendar um horário se preferir. (Mensagem de acompanhamento 1/12)',
        sender: 'ai',
        timestamp: 'Ontem 14:00',
        type: 'text',
      },
      {
        id: 'm4',
        text: 'Oi! Passando para lembrar que estamos à disposição para agendar seu exame de sangue. (Mensagem de acompanhamento 2/12)',
        sender: 'ai',
        timestamp: 'Hoje 09:00',
        type: 'text',
      },
      {
        id: 'm5',
        text: 'João, nossos horários matutinos costumam preencher rápido. Quer garantir o seu para esta semana? A Coleta Domiciliar também está disponível! (Mensagem de acompanhamento 3/12)',
        sender: 'ai',
        timestamp: 'Hoje 14:00',
        type: 'text',
      },
    ],
  },
  {
    id: 'c3',
    contactName: 'Ana Beatriz',
    platform: 'whatsapp',
    lineName: 'Agendamentos (55 11 9999-0002)',
    unreadCount: 0,
    status: 'active',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=3',
    followUpStep: 0,
    lastActivity: 'Agora',
    lostReason: 'price',
    messages: [
      {
        id: 'm1',
        text: '',
        sender: 'user',
        timestamp: '08:00',
        type: 'audio',
        fileUrl: '#',
        transcription:
          'Oi, bom dia. Eu preciso marcar uns exames de rotina que o meu médico pediu. Como eu faço?',
      },
      {
        id: 'm2',
        text: 'Bom dia, Ana! Você possui a requisição médica para esses exames? Pode nos enviar a foto.',
        sender: 'ai',
        timestamp: '08:01',
        type: 'text',
      },
      {
        id: 'm3',
        text: 'Tenho sim, vou mandar a foto.',
        sender: 'user',
        timestamp: '08:05',
        type: 'text',
      },
      {
        id: 'm4',
        text: '',
        sender: 'user',
        timestamp: '08:06',
        type: 'document',
        fileUrl: '#',
        transcription:
          'Conteúdo extraído via OCR:\n1. Hemograma Completo\n2. Glicemia em Jejum\n3. Colesterol Total',
      },
      {
        id: 'm5',
        text: 'Identifiquei os seguintes exames na sua requisição e seus respectivos preparos:\n- Hemograma Completo (Jejum de 8 a 12 horas)\n- Glicemia em Jejum (Jejum absoluto de 8 horas)\n- Colesterol Total e Frações (Jejum de 12 horas)\n\nEstão corretos?\n\nNosso laboratório possui a classificação "Padrão Ouro" pelo PNCQ, o que garante rigorosos padrões internacionais de qualidade e máxima confiabilidade nos seus resultados.\n\nPara sua comodidade, oferecemos o serviço de Coleta Domiciliar. Deseja agendar na clínica ou no conforto da sua casa?',
        sender: 'ai',
        timestamp: '08:06',
        type: 'text',
      },
    ],
  },
]

export const mockExams: ExamItem[] = [
  {
    id: 'ex1',
    code: 'HEM01',
    name: 'Hemograma Completo',
    category: 'Laboratorial',
    price: 'R$ 45,00',
    instructions: 'Jejum de 8h a 12h. Água liberada.',
  },
  {
    id: 'ex2',
    code: 'GLI01',
    name: 'Glicemia em Jejum',
    category: 'Laboratorial',
    price: 'R$ 20,00',
    instructions: 'Jejum absoluto de 8h.',
  },
  {
    id: 'ex3',
    code: 'ECG01',
    name: 'Eletrocardiograma (ECG)',
    category: 'Cardiologia',
    price: 'R$ 180,00',
    instructions: 'Não requer jejum. Evitar cremes no tórax. Levar exames anteriores se possuir.',
  },
  {
    id: 'ex4',
    code: 'RX01',
    name: 'Raio-X de Tórax',
    category: 'Imagem',
    price: 'R$ 120,00',
    instructions: 'Remover colares e objetos metálicos da região do tórax. Não requer jejum.',
  },
  {
    id: 'ex5',
    code: 'USG01',
    name: 'Ultrassonografia Abdominal',
    category: 'Imagem',
    price: 'R$ 250,00',
    instructions: 'Jejum de 8h. Tomar 4 a 6 copos de água 1h antes do exame e reter a urina.',
  },
]

export const mockImportedExams: ExamItem[] = [
  {
    id: 'ex6',
    code: 'COL01',
    name: 'Colesterol Total e Frações',
    category: 'Laboratorial',
    price: 'R$ 40,00',
    instructions: 'Jejum de 12 horas. Manter dieta habitual nos dias anteriores.',
  },
  {
    id: 'ex7',
    code: 'TGO01',
    name: 'Transaminase Oxalacética (TGO)',
    category: 'Laboratorial',
    price: 'R$ 18,00',
    instructions: 'Jejum mínimo de 4 horas.',
  },
  {
    id: 'ex8',
    code: 'TGP01',
    name: 'Transaminase Pirúvica (TGP)',
    category: 'Laboratorial',
    price: 'R$ 18,00',
    instructions: 'Jejum mínimo de 4 horas.',
  },
]

export const mockServices: ServiceItem[] = [
  {
    id: 's1',
    category: 'exam',
    name: 'Hemograma Completo',
    price: 'R$ 45,00',
    instructions: 'Jejum de 8h a 12h. Água liberada.',
  },
  {
    id: 's2',
    category: 'exam',
    name: 'Glicemia em Jejum',
    price: 'R$ 20,00',
    instructions: 'Jejum absoluto de 8h.',
  },
  {
    id: 's3',
    category: 'test',
    name: 'Eletrocardiograma (ECG)',
    price: 'R$ 180,00',
    instructions: 'Não requer jejum. Evitar cremes no tórax.',
  },
  {
    id: 's4',
    category: 'test',
    name: 'Espirometria',
    price: 'R$ 150,00',
    instructions: 'Evitar café e cigarro 2h antes.',
  },
  {
    id: 's5',
    category: 'consultation',
    name: 'Cardiologia',
    price: 'R$ 300,00',
    instructions: 'Trazer exames anteriores.',
  },
  {
    id: 's6',
    category: 'exam',
    name: 'Sumário de Urina',
    price: 'R$ 25,00',
    instructions:
      'Utilizar coletor estéril. Coletar segundo jato de urina após higienizar a região íntima. Secar bem antes de coletar.',
  },
  {
    id: 's7',
    category: 'exam',
    name: 'Cultura de Urina',
    price: 'R$ 40,00',
    instructions:
      'Utilizar coletor estéril. Coletar segundo jato de urina após higienizar a região íntima. Secar bem antes de coletar.',
  },
  {
    id: 's8',
    category: 'exam',
    name: 'Preventivo (Papanicolau / Citologia Oncótica)',
    price: 'R$ 80,00',
    instructions:
      'Não realizar o exame em período menstrual sendo as melhores datas após o 10º dia do ciclo, ideal 14 15 dia do ciclo. Mínimo de 48h após relação sexual. Não utilizar duchas vaginais, medicação ou cremes nas 48h antes da coleta do exame.',
  },
]
