import { Chat, ServiceItem } from './types'

export const mockChats: Chat[] = [
  {
    id: 'c1',
    contactName: 'Maria Silva',
    platform: 'whatsapp',
    lineName: 'Clínica Principal (55 11 9999-0001)',
    unreadCount: 2,
    status: 'pending_human',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=1',
    notes: 'Paciente diabética, requer horários matutinos.',
    history: ['Hemograma Completo (12/10/2023)', 'Consulta Cardiologia (05/01/2024)'],
    followUpStep: 0,
    lastActivity: '10:35',
    messages: [
      {
        id: 'm1',
        text: 'Olá, gostaria de saber o valor do ecocardiograma.',
        sender: 'user',
        timestamp: '10:30',
        type: 'text',
      },
      {
        id: 'm2',
        text: 'Olá! O valor do Ecocardiograma é R$ 250,00. Gostaria de agendar? Lembrando que nossa clínica possui excelência em atendimento.',
        sender: 'ai',
        timestamp: '10:30',
        type: 'text',
      },
      {
        id: 'm3',
        text: 'Sim, mas preciso saber se o Dr. Roberto atende amanhã.',
        sender: 'user',
        timestamp: '10:32',
        type: 'text',
      },
      {
        id: 'm4',
        text: 'Não tenho acesso à agenda específica do Dr. Roberto no momento. Vou transferir você para um de nossos atendentes.',
        sender: 'ai',
        timestamp: '10:32',
        type: 'text',
      },
      { id: 'm5', text: 'Por favor, aguarde.', sender: 'user', timestamp: '10:35', type: 'text' },
    ],
  },
  {
    id: 'c2',
    contactName: 'João Pedro',
    platform: 'instagram',
    lineName: '@clinicamulticanal',
    unreadCount: 0,
    status: 'active',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
    history: ['Exame Toxicológico (15/02/2024)'],
    followUpStep: 3,
    lastActivity: 'Ontem',
    surveyResult: 5,
    messages: [
      {
        id: 'm1',
        text: 'Qual o preparo para exame de sangue comum?',
        sender: 'user',
        timestamp: 'Ontem 09:15',
        type: 'text',
      },
      {
        id: 'm2',
        text: 'Para o hemograma completo, a instrução de preparo pré-analítico é jejum de 8 a 12 horas. Você pode beber água moderadamente.\n\nLembro que nosso laboratório possui a classificação "Padrão Ouro" pelo PNCQ, o que garante rigorosos padrões internacionais de qualidade e máxima confiabilidade nos resultados.\n\nGostaria de agendar na clínica ou prefere a nossa opção de Coleta Domiciliar, para realizar seu exame com todo o conforto e conveniência em casa?',
        sender: 'ai',
        timestamp: 'Ontem 09:15',
        type: 'text',
      },
      {
        id: 'm3',
        text: 'Olá João, ainda tem dúvidas sobre o preparo do seu exame? Posso ajudar a agendar um horário se preferir. (Mensagem de acompanhamento 1/12)',
        sender: 'ai',
        timestamp: 'Ontem 14:00',
        type: 'text',
      },
      {
        id: 'm4',
        text: 'Oi! Passando para lembrar que estamos à disposição para agendar seu exame de sangue. (Mensagem de acompanhamento 2/12)',
        sender: 'ai',
        timestamp: 'Hoje 09:00',
        type: 'text',
      },
      {
        id: 'm5',
        text: 'João, nossos horários matutinos costumam preencher rápido. Quer garantir o seu para esta semana? A Coleta Domiciliar também está disponível! (Mensagem de acompanhamento 3/12)',
        sender: 'ai',
        timestamp: 'Hoje 14:00',
        type: 'text',
      },
    ],
  },
  {
    id: 'c3',
    contactName: 'Ana Beatriz',
    platform: 'whatsapp',
    lineName: 'Agendamentos (55 11 9999-0002)',
    unreadCount: 0,
    status: 'active',
    avatarUrl: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=3',
    followUpStep: 0,
    lastActivity: 'Agora',
    lostReason: 'price',
    messages: [
      {
        id: 'm1',
        text: '',
        sender: 'user',
        timestamp: '08:00',
        type: 'audio',
        fileUrl: '#',
        transcription:
          'Oi, bom dia. Eu preciso marcar uns exames de rotina que o meu médico pediu. Como eu faço?',
      },
      {
        id: 'm2',
        text: 'Bom dia, Ana! Você possui a requisição médica para esses exames? Pode nos enviar a foto.',
        sender: 'ai',
        timestamp: '08:01',
        type: 'text',
      },
      {
        id: 'm3',
        text: 'Tenho sim, vou mandar a foto.',
        sender: 'user',
        timestamp: '08:05',
        type: 'text',
      },
      {
        id: 'm4',
        text: '',
        sender: 'user',
        timestamp: '08:06',
        type: 'document',
        fileUrl: '#',
        transcription:
          'Conteúdo extraído via OCR:\n1. Hemograma Completo\n2. Glicemia em Jejum\n3. Colesterol Total',
      },
      {
        id: 'm5',
        text: 'Identifiquei os seguintes exames na sua requisição e seus respectivos preparos:\n- Hemograma Completo (Jejum de 8 a 12 horas)\n- Glicemia em Jejum (Jejum absoluto de 8 horas)\n- Colesterol Total e Frações (Jejum de 12 horas)\n\nEstão corretos?\n\nNosso laboratório possui a classificação "Padrão Ouro" pelo PNCQ, o que garante rigorosos padrões internacionais de qualidade e máxima confiabilidade nos seus resultados.\n\nPara sua comodidade, oferecemos o serviço de Coleta Domiciliar. Deseja agendar na clínica ou no conforto da sua casa?',
        sender: 'ai',
        timestamp: '08:06',
        type: 'text',
      },
    ],
  },
]

export const mockServices: ServiceItem[] = [
  {
    id: 's1',
    category: 'exam',
    name: 'Hemograma Completo',
    price: 'R$ 45,00',
    instructions: 'Jejum de 8h a 12h. Água liberada.',
  },
  {
    id: 's2',
    category: 'exam',
    name: 'Glicemia em Jejum',
    price: 'R$ 20,00',
    instructions: 'Jejum absoluto de 8h.',
  },
  {
    id: 's3',
    category: 'test',
    name: 'Eletrocardiograma (ECG)',
    price: 'R$ 180,00',
    instructions: 'Não requer jejum. Evitar cremes no tórax.',
  },
  {
    id: 's4',
    category: 'test',
    name: 'Espirometria',
    price: 'R$ 150,00',
    instructions: 'Evitar café e cigarro 2h antes.',
  },
  {
    id: 's5',
    category: 'consultation',
    name: 'Cardiologia',
    price: 'R$ 300,00',
    instructions: 'Trazer exames anteriores.',
  },
]
